version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 

     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com             
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:push web